### PR TITLE
Renaming to File_Adapter, File_Engine, File_oM

### LINKED ISSUE #79: Rename solution, project files and namespaces to match with the renaming to `File_Toolkit`
#### Broken rules:

This repository will be renamed to `File_Toolkit` and its adapter to `File_Adapter`.
This renaming will need to go in parallel with the removal of the old `File_Adapter` that is contained in the [BHoM_Adapter](https://github.com/BHoM/BHoM_Adapter).

#### Suggestions to restore compliance:

As above.

### LINKED ISSUE #80: Add new adapter constructor that takes `string defaultFilename, string defaultDirectory` to match the one in File_Adapter
#### Description:

Once the Filing_Toolkit is renamed to File_Toolkit, we want to ensure that its functionality is entirely compatible with the old File_Adapter scripts. To do this, we need an additional constructor that matches the existing one in the File_Adapter.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/264

### Issues addressed by this PR

Closes #79
Closes #80

### Test files

All existing test files for File_Adapter and Filing_Toolkit must still work:
File_Adapter tests: https://burohappold.sharepoint.com/:f:/s/BHoM/EhFmrIe8YcNLqHVEXVvIWdcBfios8BdKaCD71whgINYd0A?e=lMCKoF
Filing_Toolkit tests: https://burohappold.sharepoint.com/:f:/s/BHoM/Eub2dT2Mb85Dtvv0Y09T1I4B7pzFZHcVr5NCXRuAdSpGUQ?e=h2pDm8

### Additional comments

**Note** Before merging this, we will need a separate PR on the base BHoM_Adapter that deletes the File_Adapter. This is currently todo as there are other PRs that need merging before that.

### CODE REVIEW

**Comment by alelom** [comment]
- CRUD actions should consider whether the user input is File Content or Files:
   - CreateOnly: for objects (=file content) should append new lines // for files should check if file exists, if so create new file (file name appending "copy (2)") 
   - UpdateOnly - UpdateThenCreate - DeleteThenCreate should work by implementing the read-deserialising-replacing object by object
   - At that point FullCRUD is also implementable
   - Put in discussion DeleteThenCreate pushType: consider that it could be deleting only the objects that you're trying to push (rather than all objects of that type)

- BUG: BeautifyJson not working
- Extension in adapter should default to json (error is thrown upon push now)
- Remove any newline from the input panel text for filename/folder
- Pull: Type plugged in request should filter per type

**Comment by al-fisher** [comment]
Thanks @alelom - above looks good

**Comment by al-fisher** [comment]
@alelom - note I have also raised a couple of issues which must be closed out along side this PR to ensure continuity of File Adapter functionality in the Installer

https://github.com/BHoM/Filing_Toolkit/issues/83
https://github.com/BHoM/BHoM_Installer/issues/100

@FraserGreenroyd FYI

**Comment by al-fisher** [comment]
Adding `do-not-merge` until all aligned

**Comment by alelom** [comment]
Replaced by https://github.com/BHoM/Filing_Toolkit/pull/86
to pick correct branch name for dependency.

**Pull request closed without merging**
